// pages/index.tsx

import Head from "next/head";
import HomeContainer from "@/styles/home";
import Product from "@/components/product";
import { useQuery } from "react-query";

interface ProductData {
  id: number;
  name: string;
  price: number;
  description: string;
  photo: string;
}

const fetchProducts = async (
  page: number,
  rows: number,
  sortBy: string,
  orderBy: string
): Promise<ProductData[]> => {
  const response = await fetch(
    `https://mks-frontend-challenge-04811e8151e6.herokuapp.com/api/v1/products?page=${page}&rows=${rows}&sortBy=${sortBy}&orderBy=${orderBy}`
  );
  const data = await response.json();
  return data.products;
};

const Home: React.FC = () => {
  const {
    data: products,
    isLoading,
    isError,
  } = useQuery<ProductData[]>(["products", 1, 15, "id", "DESC"], async () => {
    const data = await fetchProducts(1, 15, "id", "DESC");
    return data;
  });

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (isError || !products) {
    return <div>Error fetching data</div>;
  }

  return (
    <>
      <Head>
        <title>Desafio MKS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <HomeContainer>
        {Array.isArray(products) ? (
          products.map((product) => <Product key={product.id} data={product} />)
        ) : (
          <p>No products available</p>
        )}
      </HomeContainer>
    </>
  );
};

export default Home;
